name: Koupleless Runtime Linux Unit Test
run-name: ${{ github.actor }} pushed code

on:
  push:
    branches:
      - runtime-2.0.x

  pull_request:
    branches:
      - runtime-2.0.x

  # enable manually running the workflow
  workflow_dispatch:

env:
  WORK_DIR: .

jobs:
  unit-test-for-jdk17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: maven

      - name: Test
        run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B -U
          && sh ./check_format.sh
          && mvn test -DargLine="-Djdk.util.zip.disableZip64ExtraFieldValidation=true"

      - name: upload coverage reports to Codecov with github action
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
